{{- if .Values.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  creationTimestamp: null
  name: psp.hpa-operator
spec:
  readOnlyRootFilesystem: true
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  volumes:
  - secret
  - emptyDir
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:{{ template "hpa-operator.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: psp:{{ template "hpa-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "hpa-operator.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:{{ template "hpa-operator.fullname" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp.hpa-operator
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
